pring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}             # no default in prod
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver